name: Setup Runner and Deploy

on:
  workflow_dispatch:

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download EC2 IP Artifact
        uses: actions/download-artifact@v4
        with:
          name: ec2-ip-address

      - name: Get EC2 IP Address
        id: get-ip
        run: |
          # The IP is stored in the Terraform state file from the artifact
          IP=$(terraform output -raw instance_public_ip)
          echo "EC2_IP=$IP" >> $GITHUB_ENV

      - name: Get Runner Registration Token
        id: get-runner-token
        run: |
          TOKEN=$(curl -s -X POST -H "Authorization: token ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/orgs/Microservices-for-chatbot/actions/runners/registration-token | jq -r .token)
          echo "RUNNER_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Setup Runner on EC2 Instance
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ env.EC2_IP }} "
            # Download and configure runner
            mkdir -p /home/ubuntu/actions-runner
            cd /home/ubuntu/actions-runner
            curl -o actions-runner-linux-x64-2.316.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.316.0/actions-runner-linux-x64-2.316.0.tar.gz
            tar xzf ./actions-runner-linux-x64-2.316.0.tar.gz
            ./config.sh --url https://github.com/Microservices-for-chatbot --token \"${{ env.RUNNER_TOKEN }}\" --name \"${HOSTNAME}\" --unattended
            sudo ./svc.sh install
            sudo ./svc.sh start
          "
      
      # Step to trigger deployment workflows in each microservice repository
      - name: Trigger Microservices Deployments
        run: |
          repos="ai_service frontend chat_history"
          for repo in $repos; do
            curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Microservices-for-chatbot/$repo/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'
          done
