name: Deploy Cluster on EC2

on:
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get Private Key Content
        id: get-private-key
        run: |
          # Use a tool like `aws ssm get-parameter` or a secure method to retrieve the private key
          # For this example, we assume it's stored in a GitHub Secret
          echo "private_key_content=${{ secrets.SSH_PRIVATE_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="private_key_content=${{ env.private_key_content }}" -var="key_name=amithnv"
